# Generated by Django 2.2.14 on 2021-09-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
