# Generated by Django 2.2.14 on 2021-10-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0008_auto_20211007_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='subject',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
