# Generated by Django 2.2.14 on 2021-10-07 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0009_slider_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image2',
            field=models.URLField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='image3',
            field=models.URLField(default=2, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='image4',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='image5',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
