# Generated by Django 2.2.14 on 2021-10-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0014_auto_20211011_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='reels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='reels/')),
            ],
        ),
        migrations.DeleteModel(
            name='Play',
        ),
        migrations.DeleteModel(
            name='Poem',
        ),
    ]
